### ISSUE TITLE
Walking NPCs

### ISSUE THREAD

**Issue by ellaklara** [KTH-DH2323-Computer-Graphics/Project#5]
NPCs moving around the environment in different directions with animations.

**Comment by AdamJonsson** [comment]
Because we want to be able to run the project using WebGL, the NPC model should be fairly simple (low polygon). To make it still look good we could use a similar model as Super Hot:

![Superhot_VR_holiday_update_screenshot_2-1024x576 (1)](https://user-images.githubusercontent.com/13873828/116057273-f0bde900-a67e-11eb-822f-d6d4ebeddcb3.png)
